### ISSUE TITLE
Update cronjob schedule

### ISSUE THREAD

**Issue by sylhare** [jstrieb/github-stats#15]
Hi!

Nice work, but I believe running the github action every hour is a bit overkill. (Over 3000 commits on just generated image)
Maybe everyday or every month could be a bit more reasonable.

What do you think?

**Comment by jstrieb** [comment]
Thanks for opening this issue! You raise a good point that I did give much thought to. I think adjusting the main repository so that it updates every day instead of every hour is reasonable – expect a commit implementing this shortly.

I would be hesitant for it to update less frequently than that since I'm pretty active on GitHub and the stats images would have the potential to become outdated and inaccurate fairly quickly. 

Note that in practice, it (hopefully) shouldn't matter too much either way:
- It is possible to [view only the _real_ commits I have actually made here](https://github.com/jstrieb/github-stats/commits?author=jstrieb).
- Since the repository is now a "template," it doesn't bring any Git history with it when cloned via the recommended "Use this template" button.
- Since this repository is public, I can effectively use unlimited GitHub Actions minutes without hitting the monthly ~3,000 minute limit for private repositories.

For completeness' sake, see issue #6 – a discussion justifying committing updated images directly to the repo. It's definitely not ideal, but I've yet to find a better method that works.
