### ISSUE TITLE
Add: Dark Theme

### ISSUE THREAD

**Issue by GeneralMine** [jstrieb/github-stats#19]
It would be nice to have a dark theme like the tokyonight or dracula

**Comment by jstrieb** [comment]
Hi, thanks for the suggestion! I am probably not planning to implement many themes, but I do eventually hope to implement a single dark theme that matches the native github.com dark theme. Since the inception of this project, I have taken care to design the generated images so that they mimic the GitHub interface as closely as possible, and matching the GitHub theme would be part of that goal. 

At the moment, I am holding out for the GitHub team to offer some solution to the problem of detecting the user's dark/light setting from the README so the correct dark/light file could be used, but there have not been any updates. For more on that, see [this discussion](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981). I'm planning to wait until they implement this feature so that I don't have to undo any work down the road.

All in all, it is a good suggestion that will be implemented eventually! I will leave this issue open for documentation purposes. Thanks for checking out the project!

**Comment by andrewlalis** [comment]
Also note that in the meantime of course you can edit the SVG files inside the `templates/` directory to hack together whatever theme you want; you don't even need to know a lot about SVG, just look for the colors and change them. Then when the generator runs next, it'll use the new templates' colors.

**Comment by KnlnKS** [comment]
> It would be nice to have a dark theme like the tokyonight or dracula
You can copy my templates if you'd like. The overview one has the tokyonight theme applied. 

https://github.com/KnlnKS/KnlnKS/tree/main/templates

**Comment by jstrieb** [comment]
@KnlnKS thanks for sharing this! Do you mind if I link to it from the `README.md` file?

**Comment by KnlnKS** [comment]
> @KnlnKS thanks for sharing this! Do you mind if I link to it from the `README.md` file?
@jstrieb  Sure!

**Comment by martimdLima** [comment]
Hey,

@GeneralMine don't know if it is still of any interest to you, but i have converted the template to the colorscheme of colorized dark, so if you or anybody wants to use it you can check this link:

https://github.com/martimdLima/github-stats/tree/master/templates

@jstrieb if you want to copy or use this template in anyway feel free to do it!

**Comment by jstrieb** [comment]
Hi @martimdLima! Thanks for sharing! 

I haven't gotten around to updating the README yet, but probably will soon. I'd be happy to link to your theme as well!

**Comment by phaticusthiccy** [comment]
Darker Theme: https://github.com/phaticusthiccy/Statics/tree/master/templates
Just copy the codes :)

**Comment by chirag-droid** [comment]
material-palenight theme https://github.com/chirag-droid/github-stats/tree/master/templates

**Comment by idiotWu** [comment]
I am generating cards for both the light and dark themes in my own fork: https://github.com/idiotWu/stats. I can send a pull request if you are interested in it :).

Demo (using [the special hashes](https://twitter.com/ashtom/status/1463554157932023808) to match themes):

https://user-images.githubusercontent.com/6022672/144722590-dd671afb-67b9-40a9-ad20-c1e67b2174ca.mp4

**Comment by sme-ek** [comment]
Have you considered making the generated files transparent?

**Comment by alexcoder04** [comment]
> Have you considered making the generated files transparent?

You would still need to change the font color, so it's white on black and black on white

**Comment by jstrieb** [comment]
Thanks to all who have made suggestions in this thread! Finally got around to adding a dark theme. The one I added uses styles taken directly from the GitHub stylesheet for their dark mode, so it should (hopefully) match pretty exactly.

It looks like you can now [specify whether to use dark mode or light mode images with a URL fragment](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) that the GitHub frontend understands.

There is [some undocumented behavior](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/84) that can be used to work around the fact that the URL fragment filtering doesn't work for images inside links. I am using this workaround in the README for this repo.

In order to only have one image that works for both themes, I use [SVG fragment identifiers](https://css-tricks.com/svg-fragment-identifiers-work/), which luckily have [good browser support](https://caniuse.com/svg-fragment). 

The code changes featured:

- Adding URL fragments to the source URLs in the README:
  https://github.com/jstrieb/github-stats/blob/94ad29c9527fa212cba7d498d0024e626e7edf73/README.md#L6-L13
- Adding an `id` attribute to the SVG root that matches `gh-dark-mode-only`
  https://github.com/jstrieb/github-stats/blob/94ad29c9527fa212cba7d498d0024e626e7edf73/templates/languages.svg?short_path=66b9b62#L1
- Adding additional CSS selectors that are only used when the image is accessed with the dark mode fragment
  https://github.com/jstrieb/github-stats/blob/94ad29c9527fa212cba7d498d0024e626e7edf73/templates/languages.svg?short_path=66b9b62#L107-L115

---

Long story short, if you're using the latest version of this repo, you can include light and dark mode images like this:

``` markdown
<a href="https://github.com/jstrieb/github-stats#gh-dark-mode-only">
  <img src="https://github.com/jstrieb/github-stats/blob/master/generated/overview.svg#gh-dark-mode-only" />
  <img src="https://github.com/jstrieb/github-stats/blob/master/generated/languages.svg#gh-dark-mode-only" />
</a>
<a href="https://github.com/jstrieb/github-stats#gh-light-mode-only">
  <img src="https://github.com/jstrieb/github-stats/blob/master/generated/overview.svg#gh-dark-mode-only#gh-light-mode-only" />
  <img src="https://github.com/jstrieb/github-stats/blob/master/generated/languages.svg#gh-dark-mode-only#gh-light-mode-only" />
</a>
```

Or like this:

``` markdown
![](https://github.com/jstrieb/github-stats/blob/master/generated/overview.svg#gh-dark-mode-only)
![](https://github.com/jstrieb/github-stats/blob/master/generated/overview.svg#gh-light-mode-only)
![](https://github.com/jstrieb/github-stats/blob/master/generated/languages.svg#gh-dark-mode-only)
![](https://github.com/jstrieb/github-stats/blob/master/generated/languages.svg#gh-light-mode-only)
```

![](https://github.com/jstrieb/github-stats/blob/master/generated/overview.svg#gh-dark-mode-only)
![](https://github.com/jstrieb/github-stats/blob/master/generated/overview.svg#gh-light-mode-only)
![](https://github.com/jstrieb/github-stats/blob/master/generated/languages.svg#gh-dark-mode-only)
![](https://github.com/jstrieb/github-stats/blob/master/generated/languages.svg#gh-light-mode-only)

Glad to finally be able to close this issue after more than a year!
