### ISSUE TITLE
Counting stars and forks from forks

### ISSUE THREAD

**Issue by GCrispino** [jstrieb/github-stats#4]
Hi!

I just generated stats for my profile, and it resulted in the following:
![image](https://user-images.githubusercontent.com/8827509/95789164-63eba900-0cb3-11eb-94c8-caaca842bbc4.png) (the true file is located [here](https://github.com/GCrispino/github-stats/blob/master/generated/overview.svg))

The stats looks strange, because I counted and I don't know if I even have 10 stars, and it says I got more than 2000. Does the action count stars and forks including forks? I realize this might be a design decision, but I figured I might ask.

Anyway, congratz on the tool! It looks nice and it has valuable information such as repository views and all-time contributions.

**Comment by jstrieb** [comment]
Hi! Thanks for your question and for using the project!

The action does count stars and forks of repositories that a user has forked and contributed to (if I remember correctly they have to have contributed for it to count). Items on my to-do list for this project include adding support for command-line options to configure the way queries are made so that this can be disabled. This would amount to adding some restrictions added to the GitHub GraphQL API query that assembles the stars and forks data, as well as the list of repositories to get stats for.

Including this data was a design decision because I recognize that there are users on GitHub who primarily contribute to large open source projects, but do not have many projects themselves, and I didn't want the stats to under-represent their activity. I essentially opted for false positives rather than false negatives on whether users have "earned" the stars/forks that are listed for them.

I'll leave this issue open until I get around to cleaning things up and adding the option to disable this. Thanks again for your interest!

**Comment by GCrispino** [comment]
Hi @jstrieb ! Thanks for answering.
This decision makes sense. Having an option to filter repositories would be a good solution in my opinion. I'd be also willing to help, if you think this would help in the process.

**Comment by rahul-jha98** [comment]
Hi @jstrieb! 
I agree with @GCrispino that it would be nice to have an option to only consider repositories that aren't forked for generating stats. If no one is working on the issue I can try implementing it.
I was thinking of using an environment secret called IGNORE_FORKED_REPOSITORIES as a flag variable. So, if user has that secret set to any value, we can ignore the forked repositories else we will consider it. If you guys have other ideas I can try that as well.

**Comment by rahul-jha98** [comment]
@jstrieb Please checkout the PR. I implemented the logic I mentioned in previous comment.

**Comment by jstrieb** [comment]
Noting here for completeness: I just merged the PR from @rahul-jha98 that addresses this issue. It uses an environment variable called `EXCLUDE_FORKED_REPOS`. One day, I may change it to a command-line argument, but probably not anytime soon.

Thanks all for the feedback, and help getting this feature added!
