### ISSUE TITLE
Ability to output a debug dump

### ISSUE THREAD

**Issue by Drarig29** [jstrieb/github-stats#54]
Some days ago, a new language added in my [`languages.svg`](https://github.com/Drarig29/Drarig29/blob/7cde7af299d39d9179d742d48a09266d8c449dc4/generated/languages.svg) file.

The thing is, the only "link" I have with this language is that I recently viewed this repo, which is written in Zig: https://github.com/Jarred-Sumner/bun

I know that I can exclude this language (because I don't want to have it in my stats), but I'd be curious to have some logs or even enable some kind of debug dump file, to see where does this language comes from in my stats. What repo is responsible for adding this language in my stats.

I tried to run this template repo locally, but it generated empty images. Even when I set `ACCESS_TOKEN` and `GITHUB_ACTOR` as environment variables.

**Comment by jstrieb** [comment]
Hi @Drarig29! I've never had any trouble running this locally, so I have not thought about adding a debug flag or detection of a `DEBUG` environment variable until now.

I think it could be good to add, with the caveat that a major warning should be attached so users know that they risk leaking information about their private repositories.

I'll keep this open until I can get around to adding this.

**Comment by jstrieb** [comment]
In the meantime, I'm happy to help debug why this isn't working locally. Are you running the project from the command line, or from inside an IDE?

**Comment by Drarig29** [comment]
> In the meantime, I'm happy to help debug why this isn't working locally. Are you running the project from the command line, or from inside an IDE?

From the command line :)

**Comment by Drarig29** [comment]
I may be missing something...

**Comment by jstrieb** [comment]
Are you setting the environment variables using the following commands? Are you making sure to set both the `ACCESS_TOKEN` and `GITHUB_TOKEN` environment variables? 

``` bash
export ACCESS_TOKEN=... 
export GITHUB_TOKEN=... 
```

**Comment by Drarig29** [comment]
What should I set as a `GITHUB_TOKEN` then?

I don't understand the need of this token, as its use is commented out here:

https://github.com/jstrieb/github-stats/blob/2d9b3bf580517b5b1be37a8d8f0f36dd92b452d5/generate_images.py#L104

**Comment by jstrieb** [comment]
> I don't understand the need of this token, as its use is commented out

You're right, it shouldn't be necessary. That's my bad for suggesting it. 

If I remember correctly, that environment variable is left over from code that has since been removed that was supposed to fall back on the GitHub token available in the Actions workflow if no access token secret was provided. That feature never really worked right, so I dropped it.

Is it possible that your access token does not have the correct permissions? That shouldn't be an issue if it's working in the Actions workflow, but just a shot in the dark.

**Comment by Drarig29** [comment]
I just double checked my access token and it works now!

But it's not generating the same stats as in my GitHub profile...

I set `GITHUB_ACTOR` as `Drarig29/github-stats` and then I tried with `Drarig29`. But I'm always getting the same - wrong - stats. Any idea?

![image](https://user-images.githubusercontent.com/9317502/140435450-e81656bf-78fa-4584-9f52-aa6f35ad5963.png)

**Comment by Drarig29** [comment]
Up

Sorry but I think you don't receive the notifications when we don't have a lot of time between each answer :)

**Comment by jstrieb** [comment]
Hey @Drarig29, sorry for the late reply – haven't had much time for this project lately. 

Did you ever get this working? I'm going to guess that this issue is from contributing to a popular repo, or possibly from being a member of an organization with popular repos. For some references, it's worth looking through other issues (both open and closed) to see how others solved having what seemed to be the wrong number of stars, forks, etc.

**Comment by Drarig29** [comment]
Hey! For now, gave up this idea so I used `EXCLUDED_LANGS` to exclude the added language.

**Comment by jstrieb** [comment]
Good to know! I'll close this for now, but feel free to reopen it if there is more to discuss.
